init
gemini-testing/hermione-url-decorator pull request #1
Opened 2016-09-13 07:13 UTC by DudaGod

2016-09-13 07:29 UTC, DudaGod commented
/cc @j0tunn @eGavr @sipayRT @tormozz48 @rostik404

2016-09-13 09:37 UTC, eGavr commented on LICENSE
> +Copyright (c) 2014 Sergej Tatarincev
Sergej Tatarincev? 😄

2016-09-13 09:38 UTC, eGavr commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) which is intended to add additional params to the current browser url (at the moment adds only query params). You can read more about
params –> parameters

2016-09-13 09:38 UTC, eGavr commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) which is intended to add additional params to the current browser url (at the moment adds only query params). You can read more about
`at the moment adds only query params` – лишняя фраза

2016-09-13 09:39 UTC, eGavr commented on README.md
> +You need to connect the plugin in the config `hermione`:
Add plugin to your configuration file:

2016-09-13 09:41 UTC, eGavr commented on README.md
> +PLATFORM=desktop HERMIONE_URL_QUERY_TEXT='foo=bar&baz=boo' hermione
давай как можно проще пример приведем:

HERMIONE_URL_QUERY_TEXT='foo=bar&baz=boo' –> HERMIONE_URL_QUERY_TEXT='ololo'

2016-09-13 09:41 UTC, eGavr commented on README.md
> +PLATFORM=desktop HERMIONE_URL_QUERY_TEXT='foo=bar&baz=boo' hermione
и еще можно привести пример.. типо.. вот такой урл вы указываете в тесте,  а на самом деле будем ходить по такому-то урлу.

2016-09-13 09:42 UTC, eGavr commented on README.md
> +it should be an object and his values strings:
his values should be strings

2016-09-13 09:43 UTC, eGavr commented on README.md
> +which must start with `HERMIONE_URL_QUERY_`.
must какое-то грубое слово)

давай should использовать? ты вроде и ниже используешь should

2016-09-13 09:43 UTC, eGavr commented on README.md
> +If query parameters are specified via environment variables and in the config file, then
можно `, then` заменить на тире, кажется.

2016-09-13 09:44 UTC, eGavr commented on README.md
> +values from environment variables takes precedence.
`variables takes precedence`

ты слово `precedence` знал изначально или в переводчике нашел? :) чем проще запишешь, тем лучше, поэтому почему не так:

`values from environment variables will be used`

2016-09-13 09:45 UTC, eGavr commented on README.md
> +* **query** (optional) `Object` - the list of query parameters, are added to the parameters of url
ты и тут что-то пишешь про опцию `query`, и выше что-то писал. все в одном месте про это сгруппируй

2016-09-13 09:47 UTC, eGavr commented on lib/defaults.js
> +        queryEnvStarts: 'HERMIONE_URL_QUERY_'
если я ничего не перепутал, то ты это значение только в тестах используешь... не надо так делать

2016-09-13 09:52 UTC, eGavr commented on lib/index.js
> +    const urlEnvParams = parseUrlEnvParams();
parseUrlEnvParams –> parseConfigFromEnv ?

2016-09-13 09:59 UTC, eGavr commented on README.md
> +    }
я подумал, что API вот такое будет удобнее:

```js
'hermione-url-decorator': {
    enabled: true // false
    url: {
        query: {
            text: 'ololo',
            // и т д
        }  
    }
}
```

2016-09-13 10:01 UTC, eGavr commented on lib/index.js
> +    const query = getQuery(urlEnvParams.query, opts.query);
Не надо вызывать валидацию в функциях `get`, сначала валидируешь значение, а потом отдельной функцией их получаешь.

------------------

Ты зря сильно завязываешься на поле `query`. Реализовывай архитектуру с мыслями, что в перспективе мы захотим переопределять не только `query`, и когда мы захотим править под это код, нам хочется как можно меньше что-то в коде менять:

```js
validateOptions(opts);

const configFromEnv = parseConfigFromEnv();
const config = _.extend(opts.url, configFromEnv); // так автоматически переопределим конфиг переменными среды окружения

hermione.on(hermione.events.SESSION_START, (browser) => decorateUrl(browser, config))
```

2016-09-13 10:02 UTC, eGavr commented on lib/url-decorator.js
> +    const baseUrlFn = browser.url.bind(this);
можно без `bind`-а, посмотри тут – https://github.yandex-team.ru/search-interfaces/hermione-assert-metrics/blob/master/lib/commands/url-decorator.js#L57-L69

2016-09-13 10:03 UTC, eGavr commented on lib/url-decorator.js
> +        uri = uri ? addQueryToUri(uri, query) : uri;
снова завязался на `query`

2016-09-13 10:03 UTC, eGavr commented on lib/url-decorator.js
> +    }, true);
у нас пошла привычка писать в комменте, зачем здесь `true` :)

2016-09-13 10:05 UTC, eGavr commented on lib/url-decorator.js
> +    });
как-то сильно сложно :) посмотри как декорируется url здесь – https://github.yandex-team.ru/search-interfaces/hermione-assert-metrics/blob/master/lib/commands/url-decorator.js#L36-L45

2016-09-13 10:05 UTC, eGavr commented on lib/url-env-parser.js
> +    let index;
надо переменные поближе к месту использования

2016-09-13 10:06 UTC, eGavr commented on lib/url-env-parser.js
> +        .pickBy((val, key) => _.startsWith(key, urlEnvStarts))
я бы, честно говоря, прям тут захардкодил в константе `urlEnvStarts`

2016-09-13 10:07 UTC, eGavr commented on lib/defaults.js
> +    });
вообще... эти значение не совсем про конфиг :)

про конфиг только поля `enabled` и `url`

2016-09-13 10:12 UTC, eGavr commented on lib/url-env-parser.js
> +        }, {})
очень сложная функция.

почему нельзя ключ расплиттить по символу `_`, а затем заюзать обычный `_.set` ?

```
const splitted = key.split('_');

return _.set(res, splitted, val);
```

???

может `as is` мой код не работает, но должно быть что-то в этом духе

2016-09-13 10:19 UTC, eGavr commented on .travis.yml
> +      env: COVERALLS=1
а почему такой странный порядок?

2016-09-13 10:20 UTC, eGavr commented on lib/index.js
> +                `${chalk.red('hermione-url-decorator')}: query.${key} param must be a string`
не надо ничего цветом выводить :)

достаточно упасть со стэктрейсом

2016-09-13 10:23 UTC, eGavr commented on test/lib/index.js
> +const QEmitter = require('qemitter');
зачем тебе именно `QEmitter` ? можно испозовать обычный нативный. нам тут пофиг в тестах, кто триггерит событие)

2016-09-13 10:26 UTC, eGavr commented on test/lib/index.js
> +    };
не критично... но! если поменяем API Гермионы, то тут все сломается, можно не хардкодить event-ы, а прям зарекваерить их https://github.yandex-team.ru/search-interfaces/hermione-assert-metrics/blob/master/test/lib/index.js#L4

Это publicAPI Гермионы, так можно делать. Да, получим лишнюю `devDependecy`, но зато надежнее. На скорость установки зависимостей в проде это не влияет, поэтому норм.

2016-09-13 10:26 UTC, eGavr commented on test/lib/index.js
> +    };
хотя не...

 достаточно критично 😄

2016-09-13 10:27 UTC, DudaGod commented on .travis.yml
> +      env: COVERALLS=1
не знаю. Я взял у Андрюхи, а он брал у блонда, который вроде как с этим подробно разбирался.

2016-09-13 10:28 UTC, eGavr commented on test/lib/index.js
> +        it(`env vars starting with "${queryEnvStarts}" and "opts.query" are not set`, () => {
тест уйдет, когда логику в коде чуть поменяем

2016-09-13 10:30 UTC, eGavr commented on test/lib/index.js
> +    describe(`env vars starting with "${queryEnvStarts}" are NOT set`, () => {
я бы не выносил тесты в этот и предыдущий `decribe`.

Просто такие вот подряд тесты:

1. указаны опции в конфиге, а через env не указаны
2. указаны опции через env, а через cli не указаны
3. указаны опции в конфиге и через env (пересекающиеся)
4. не указано ничего

2016-09-13 10:32 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should replace delim "&" to ";" in new query url', () => {
ты уверен,  что это все надо делать? вроде методы нативного модуля `url` и так умные и все это уже учитывают. Или браузер будет это учитывать... ну это странно валидировать

2016-09-13 10:32 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should not redefine "url" method if it was called without query params', () => {
should not redefine "url" method if it was called without parameters

2016-09-13 10:33 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should concat query params with the same params in current query url', () => {
мы вроде договорились, что надо переопределять

2016-09-13 10:34 UTC, eGavr commented on test/lib/url-env-parser.js
> +        sandbox.restore();
давай `sandbox.restore()` последним выражение в `afterEach`. Прости.. но аж глаз режет 😄

2016-09-13 10:34 UTC, eGavr commented on test/lib/url-env-parser.js
> +        _.forOwn(process.env, (value, key) => {
`forEach` чем не подошел?

2016-09-13 10:36 UTC, eGavr commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
Не-а! не так оно должно отработать..

`HERMIONE_URL_RESOURCE_PATH_DIR`

должно распарсится в 

```js
{
    RESOURCE: {
        PATH: {
            DIR: 'hello/world'
        }
    }
}
```

2016-09-13 10:38 UTC, eGavr commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
а стоп... тогда мы не сможем задать query параметр с подчеркиванием...

2016-09-13 10:38 UTC, j0tunn commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
а как можно указать параметр в camelCase?

2016-09-13 10:40 UTC, eGavr commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
Да, не получится сделать прям как я хотел, и парсинг параметров, который я предложил тоже работать не будет, но твоя функция `transform` в коде все равно очень сложная, ее надо рефакторить.

2016-09-13 10:41 UTC, eGavr commented on test/lib/url-env-parser.js
> +    let expectedResult;
не надо их глобальными делать... 

ближе к месту использования, плз.

2016-09-13 10:42 UTC, eGavr commented on test/lib/url-env-parser.js
> +        assert.deepEqual(result, expectedResult);
зачем переменная `result` ?

че не просто

```js
assert.deepEqual(parseUrlEnvParams(), expectedConfig);
```

2016-09-13 10:43 UTC, eGavr commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY_HAIR'] = 'ginger';
ginger...

что-то знакомое?

мультик такой был с главной героиней с этим именем? 😄

2016-09-13 10:45 UTC, eGavr commented on .travis.yml
> +      env: COVERALLS=1
бездумный копипаста !!11 ай-ай-ай!

ну тебе не режет глаз?

Почему бы подряд не указать сначала языки, в которых тестируешь, а затем `env` ?

ну или сначала `env`,  а затем языки

2016-09-13 10:51 UTC, j0tunn commented on .travis.yml
> +      env: COVERALLS=1
почитайте синтаксис yml. Оба :)

2016-09-13 11:44 UTC, DudaGod commented on .travis.yml
> +      env: COVERALLS=1
Мне не режет =)

Почитал про синтаксис yml.
Текущий вариант можно представить в виде:
```js
[
    {node_js: 4, env: 'COVERALLS=1'},
    {node_js: 6}
]
```

То есть запустится только для ноды 4ой версии. Под 6ой версией видимо проблемы у coveralls - не смог об этом найти инфу в инете.

2016-09-13 11:54 UTC, sipayRT commented on .travis.yml
> +      env: COVERALLS=1
> Под 6ой версией видимо проблемы у coveralls - не смог об этом найти инфу в инете.

просто тебе незачем запускать подсчет покрытия 2 раза - он будет одинаковый для обоих версий ноды ;)

2016-09-13 11:59 UTC, DudaGod commented on README.md
> +values from environment variables takes precedence.
я его узнал когда configparser пилил, оно в cli.js используется в gemini.

Ок, сейчас проще напишу.

2016-09-13 12:15 UTC, DudaGod commented on lib/defaults.js
> +        queryEnvStarts: 'HERMIONE_URL_QUERY_'
еще юзаю в `lib/url-env-parser.js`. Ок, тогда в констаты унесу.

2016-09-13 12:26 UTC, DudaGod commented on lib/index.js
> +    const urlEnvParams = parseUrlEnvParams();
Не понял, чем parseConfigFromEnv лучше.
По сути данная функция должна парсить переменные среды окружения которые начинаются с `HERMIONE_URL_`. Кажется, что parseUrlEnvParams больше соответствует данному описанию.

2016-09-13 12:28 UTC, DudaGod commented on lib/index.js
> +    const urlEnvParams = parseUrlEnvParams();
Ниже уже прочитал, чем лучше =)

2016-09-13 12:34 UTC, DudaGod commented on lib/index.js
> +    const query = getQuery(urlEnvParams.query, opts.query);
Понял, согласен, сейчас исправлю.

Только валидацию поставлю после extend-а. Так как если в конфиге объект url задан неверно, а я его переопрделил на правильный с помощью переменных среды окружения, то хотелось бы чтобы плагин не падал.

2016-09-13 13:05 UTC, DudaGod commented on lib/index.js
> +                `${chalk.red('hermione-url-decorator')}: query.${key} param must be a string`
А почему бы кроме стек трейса не вывести еще и текст ошибки? 
По тексту же намного быстрее станет понятно почему гермиона упала. Пользователь прочитает текст и поймет, что параметры урла должны быть строками.

2016-09-13 13:37 UTC, eGavr commented on lib/index.js
> +                `${chalk.red('hermione-url-decorator')}: query.${key} param must be a string`
Нет. Текст ошибки + стэктрейс – это самое оно, не надо для девочек выводит красивенько и с цветочками (ИМХО)

2016-09-13 13:44 UTC, DudaGod commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
в camelCase сейчас никак не указать, в текущей реализации я специально все к нижнему регистру привожу. А разве есть необходимость указывать параметры в camelCase?

2016-09-13 14:02 UTC, j0tunn commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
ну вроде стандарт не запрещает параметры в camelCase

2016-09-13 14:15 UTC, eGavr commented on test/lib/url-env-parser.js
> +                'path_dir': 'hello/world'
ну мы вроде разобрались голосом и пришли к тому, что там просто надо код порефакторить, логику не менять

2016-09-13 14:33 UTC, eGavr commented
Название пулл-реквеста так себе :)

2016-09-13 15:28 UTC, DudaGod commented on lib/url-decorator.js
> +    });
посмотрел, но у тебя там конкатить не нужно, а просто переопределять. Поэтому сильно легче не получается =(

2016-09-13 15:29 UTC, DudaGod commented on lib/defaults.js
> +    });
теперь еще и `concat`

2016-09-13 15:31 UTC, DudaGod commented on lib/url-env-parser.js
> +    let index;
я хотел их переопределять, а так каждый раз в цикле будет создаваться новая переменная.

2016-09-13 15:35 UTC, DudaGod commented on lib/url-env-parser.js
> +        }, {})
Проблема с `exp_flags` - который должен быть целым параметром и не сплитится. Я изначально так же хотел, как ты предложил.

2016-09-13 15:53 UTC, eGavr commented on lib/url-decorator.js
> +    });
ну пришли решение окончательное, будем смотреть :)

2016-09-13 16:01 UTC, DudaGod commented on lib/url-env-parser.js
> +        }, {})
```js
return _(process.env)
        .pickBy((val, key) => _.startsWith(key, 'HERMIONE_URL_'))
        .mapKeys((envVal, envKey) => _.replace(envKey, 'HERMIONE_', '').toLowerCase())
        .transform((res, val, key) => {
            let keys = _.split(key, '_');
            keys.push(keys.splice(2).join('_'));
            _.set(res, keys, val)
        }, {})
        .value();
```
Текущий вариант.
Все равно сложно получается так как `exp_flags` не должен разбиваться.

2016-09-13 16:02 UTC, DudaGod commented on lib/index.js
> +                `${chalk.red('hermione-url-decorator')}: query.${key} param must be a string`
тогда надо черным хуячить для мужиков =)

2016-09-13 16:15 UTC, DudaGod commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY_HAIR'] = 'ginger';
Был =) Так же переводится как цвет волос - рыжая.

2016-09-13 16:38 UTC, DudaGod commented on lib/url-decorator.js
> +    });
Сейчас она вот так выглядит:

```js
const updateUri = (uri, query, concat) => {
    const parsedUri = url.parse(uri, true);

    if (concat && !_.isString(concat)) {
        concat = '';
    }

    _.forEach(query, (value, key) => {
        _.update(parsedUri, `query.${key}`, (currValue) => {
            return concat === false || !currValue
                ? value
                : `${currValue}${concat}${value}`
        });
    });

    // if don't remove 'search' field, then 'url.format' doesn't create new uri with added query params
    return url.format(_.omit(parsedUri, 'search'));
};
```

2016-09-13 16:45 UTC, DudaGod commented on test/lib/index.js
> +        it(`env vars starting with "${queryEnvStarts}" and "opts.query" are not set`, () => {
Не уйдет. Я теперь смотрю если нет в итоговом конфиге поля url или он пустой, то я просто выхожу из плагина. То есть url мне нечем декорировать.

2016-09-13 17:17 UTC, eGavr commented on lib/url-env-parser.js
> +        }, {})
```js
const HERMIONE_URL_STR = 'HERMIONE_URL_'; // над названием можно поработать

return (process.env)
    .pickBy((val, name) => _.startsWith(name, HERMIONE_URL_STR))
    .mapKeys((val, name) => _.replace(name, HERMIONE_URL_STR, '').toLowerCase())
    .transform((res, val, name) => {
        // это все можно (нужно) в отдельную функцию вынести
        const matched = name.match(/^(.*?)_(.*)/);

        if (!matched) throw new Error('...');

        return _.set(res, [matched[1], matched[2]], val);
    }, {})
    .value()
```

2016-09-13 17:18 UTC, eGavr commented on lib/index.js
> +                `${chalk.red('hermione-url-decorator')}: query.${key} param must be a string`
надо нативным цветом хуячить ;)

2016-09-13 17:20 UTC, eGavr commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY_HAIR'] = 'ginger';
Так че за мульт то,  ну?

2016-09-13 17:27 UTC, eGavr commented on lib/url-decorator.js
> +    });
```js
if (concat && !_.isString(concat)) {
    concat = '';
}
```

это надо где-то делать раньше, где-то в месте инициализации конфига

-----------

В функцию бы передавал `uri` и полный `config`

-----------

```js
_.forEach(query, (value, key) => {
        _.update(parsedUri, `query.${key}`, (currValue) => {
            return concat === false || !currValue
                ? value
                : `${currValue}${concat}${value}`
        });
    });
```

всю эту магию через https://lodash.com/docs/4.15.0#assignInWith не проще/короче будет записать?

2016-09-13 18:19 UTC, DudaGod commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY_HAIR'] = 'ginger';
про зубатую рыжую девочку и ее друга негра с железной челюстью

2016-09-13 18:57 UTC, DudaGod commented on lib/url-decorator.js
> +    });
Да получилось короче, использовал `assignWith` вместо `assignInWith`. Так как url.parse возвращает обычный объект и query у нас тоже обычный объект ни от чего не унаследованный.

По поводу `search` - уверен, достаточно только его. По крайней мере для переопределения query параметров. Возможно если нужно переопределить путь, то нужно удалять и path.

2016-09-13 20:06 UTC, eGavr commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY_HAIR'] = 'ginger';
еееее

точняк! я вспомнил 😄

2016-09-14 09:47 UTC, eGavr commented on README.md
> +which should start with `HERMIONE_URL_` or specify in the `hermione` config file.
or specify **them** in

2016-09-14 09:48 UTC, eGavr commented on README.md
> +
лишняя пустая строка

2016-09-14 09:49 UTC, eGavr commented on README.md
> +For instance you have next url: `http://localhost/test/?name=hermione` and you want concat current name query parameter with `garri` using `;` as delimiter.
запятая после `For instance`

2016-09-14 09:49 UTC, eGavr commented on README.md
> +For instance you have next url: `http://localhost/test/?name=hermione` and you want concat current name query parameter with `garri` using `;` as delimiter.
you want **to** concat

2016-09-14 09:49 UTC, eGavr commented on README.md
> +For instance you have next url: `http://localhost/test/?name=hermione` and you want concat current name query parameter with `garri` using `;` as delimiter.
garry –> harry :)

2016-09-14 09:50 UTC, eGavr commented on README.md
> +For instance you have next url: `http://localhost/test/?name=hermione` and you want concat current name query parameter with `garri` using `;` as delimiter.
`name query`

слово `name` надо как-то выделить (или жирным или бэктиками, лучше, кажется, жирным)

2016-09-14 09:50 UTC, eGavr commented on README.md
> +
пустая строка лишняя

2016-09-14 09:51 UTC, eGavr commented on README.md
> +In this example if the concat would not have been set, then name query parameter will be
would not have been set –> is not set

2016-09-14 09:51 UTC, eGavr commented on README.md
> +overriden: `http://localhost/test/?name=garri`
ничего не сказал в доке про то, что если указала `concat: true`

2016-09-14 09:52 UTC, eGavr commented on README.md
> +* **concat** (optional) `Boolean|String` - enable/disable concatenation of url parameters or specify the delimiter; by default is false
false выдели

2016-09-14 09:52 UTC, eGavr commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
are added -> which should be added

2016-09-14 09:53 UTC, eGavr commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
His final values should be a strings

поясни...

2016-09-14 09:54 UTC, eGavr commented on lib/index.js
> +    });
зачем `assingWith` ? вроде достаточно просто `assign` или `extend`

2016-09-14 09:56 UTC, eGavr commented on lib/index.js
> +    });
Вынеси это в отдельную функцию, попробуй без `_.update`

2016-09-14 09:57 UTC, eGavr commented on lib/url-decorator.js
> +    const customizer = (objValue, srcValue) => {
сделаем вид, что я не видел название этой функции, а ты ее незаметно переименуешь во что-то адекватное :)

2016-09-14 09:57 UTC, eGavr commented on lib/url-decorator.js
> +
кажется, что дишняя пустая строка

2016-09-14 09:59 UTC, eGavr commented on lib/url-env-parser.js
> +            '(hermione-url-decorator): url env vars should be set in snake case with minimium 3 delimiters'
в стэктрейсе и так будет видно откуда прилетела ошибка :)

причем тут особо пользователю не важно откуда она прилетела.

`url env vars should be set in snake case with minimium 3 delimiters`

фигня, надо подробнее описание, которое не завязано на количество символов `_`

2016-09-14 10:00 UTC, eGavr commented on lib/url-env-parser.js
> +        .pickBy((val, key) => _.startsWith(key, URL_ENV_STARTS))
URL_ENV_STARTS –> URL_ENV_BEGINNING или URL_ENV_START ?

2016-09-14 10:01 UTC, eGavr commented on test/lib/index.js
> +const URL_ENV_STARTS = 'HERMIONE_URL_';
если напрягает писать это и тестах и в коде, то можно создать файл `./lib/constants.js`:

```js
module.exports = {
    URL_ENV_STARTS: 'HERMIONE_URL_'
};
```

2016-09-14 10:03 UTC, eGavr commented on lib/index.js
> +        return value || _.isString(value) ? value : false;
а почем не просто 

`return value` ?

2016-09-14 10:05 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, config);
почему `exactly` ?

2016-09-14 10:07 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, {concat: false, url: {query: {foo: 'bar'}}});
`concat: false` лишняя инфа для теста

2016-09-14 10:07 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, {concat: false, url: {query: {text: 'fromEnv'}}});
`concat: false` лишняя инфа для теста

2016-09-14 10:08 UTC, eGavr commented on test/lib/index.js
> +    it('should override "config.concat" value to empty string', () => {
if it specified as `true`

2016-09-14 10:09 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, {concat: '', url: 'test'});
`url: 'test'` – лишня инфа

2016-09-14 10:09 UTC, eGavr commented on test/lib/index.js
> +                    text: false
а мы не хотим это просто  к строке приводить и все ?

2016-09-14 10:10 UTC, eGavr commented on test/lib/index.js
> +        it(`env vars starting with "${URL_ENV_STARTS}" and "url" from config are empty`, () => {
env vars are not specified and ...

2016-09-14 10:11 UTC, eGavr commented on test/lib/url-decorator.js
> +    beforeEach(() => sandbox.stub(process, 'cwd'));
а зачем ?

2016-09-14 10:13 UTC, eGavr commented on test/lib/url-decorator.js
> +        decorateUrl(browser, {concat: '&', url: {query: {foo: 'bar', baz: 'boo'}}});
наш декоратор долже уметь добавлять новые параметры, которых нет, без дополнительного указания опции `concat`

2016-09-14 10:14 UTC, eGavr commented on test/lib/url-decorator.js
> +
нужен тест на то, когда concat=true

2016-09-14 10:15 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it('should throw error if env var not set in snake case', () => {
необязательно SNAKE_CASE

а если я вот так захочу

`HERMIONE_URL_QUERY_EXP-FLAGS=ololo`

ожидается, что добавится `query` параметр `exp-flags` со значением `ololo`

2016-09-14 10:17 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it('should throw error if env var has less than three delimiters', () => {
может просто скажем `is invalid` ?

еще я подумал, что вообще падать не надо....

А вдруг кто-то передаст переменную `HERMIONE_URL_QUERY`, которая несет какой-то смысл вне плагина? тогда наш плагин просто будет падать.

2016-09-14 10:23 UTC, eGavr commented
Мне в целом нравится  :) 

правь последние замечания,  призывай на финальное ревью.

2016-09-14 13:20 UTC, DudaGod commented on README.md
> +
не понял почему они лишние? А сверху не лишние? Так же легче текст читается с переносами, а окончательный вид по идеи будет одинаковый. То есть сам markdown проставит перенос после блока с кодом.

2016-09-14 13:29 UTC, DudaGod commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
Хотел указать, что конечные значения должны быть строками, то есть:
```js
{
    url: {
        query: {
            name: 'vasya'  // то есть я хотел про это значение написать
        }
    }
}
```

2016-09-14 13:36 UTC, eGavr commented on README.md
> +
ну как хочешь :)


мне больше нравится без лишний строк

2016-09-14 13:48 UTC, DudaGod commented on lib/index.js
> +    });
Допустим если я не задал environment variables, то `parseConfigFromEnv()` вернет пустой объект. В итоге получается, что `configFromEnv = {url: {}}`
После чего при использовании `assign` или `extend` параметр `url` установленный в конфиге будет изменен на пустой объект в независимости от того есть в нем значения или нет.

Поэтому нашел только такой вариант.

2016-09-14 13:57 UTC, eGavr commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
я понимаю, что он проверяет,  я скорее про то, что описание так себе

2016-09-14 13:59 UTC, eGavr commented on lib/index.js
> +    });
тогда давай эту штуку в отдельную функцию

2016-09-14 13:59 UTC, DudaGod commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
Да я понял, сейчас сделаю, что бы это было не обязательным. Может пусть все, что не false и не true в строки приводятся.

2016-09-14 14:01 UTC, eGavr commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
я бы все в строки переводил..

ну типо если я указал

```
query: {
    flag: true
}
```
то  я тоже ожидаю, что добавится quert параметр flag со значением true

2016-09-14 14:07 UTC, DudaGod commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
да, я понял. Но `false` должен передаваться as is - по нему смотрю нужно переопределяться значение или конкатить. А при `true` переопределить в пустую строку, а остальные кейсы скормить `_.toString()`

2016-09-14 14:14 UTC, DudaGod commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, are added to current browser url. His final values should be a strings
ааа, все я понял, сейчас сделаю. 
Я провтыкал и писал почему то сюда про `concat` опцию, хотя разговор о значениях urla =)

2016-09-14 15:59 UTC, DudaGod commented on lib/url-env-parser.js
> +            '(hermione-url-decorator): url env vars should be set in snake case with minimium 3 delimiters'
Да, согласен что не очень сообщение об ошибке.
Пока исправил на это: `url env vars should be set in snake case, for example HERMIONE_URL_QUERY_NAME`

2016-09-14 16:03 UTC, DudaGod commented on lib/index.js
> +        return value || _.isString(value) ? value : false;
Я это уже исправил.
Теперь это выглядит вот так:
```js
const configureConcat = (concat) => {
    if (concat === true) {
        return '';
    }

    return concat !== false ? _.toString(concat) : false;
};
```

2016-09-14 16:06 UTC, DudaGod commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, config);
Хочу проверить что функция вызвана именно с двумя конкретными аргументами, без `exactly` она может быть вызвана хоть с 10ю.

2016-09-14 16:09 UTC, j0tunn commented on lib/index.js
> +        return value || _.isString(value) ? value : false;
```js
switch (concat) {
    case true: return '';
    case false: return false;
    default: return _.toString(concat);
}
```

2016-09-14 16:19 UTC, DudaGod commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, {concat: false, url: {query: {foo: 'bar'}}});
Тогда нужно конкретный параметр проверять:
```js
assert.deepEqual(decorateUrl.firstCall.args[1].url, {query: {foo: 'bar'}});
```

2016-09-14 16:28 UTC, DudaGod commented on test/lib/index.js
> +                    text: false
хотим

2016-09-14 17:04 UTC, DudaGod commented on test/lib/url-decorator.js
> +    beforeEach(() => sandbox.stub(process, 'cwd'));
не помню, видимо юзал для чего то =)
Удалил.

2016-09-14 17:06 UTC, eGavr commented on lib/url-env-parser.js
> +            '(hermione-url-decorator): url env vars should be set in snake case with minimium 3 delimiters'
я бы NAME заменил на TEXT

2016-09-14 17:06 UTC, eGavr commented on lib/index.js
> +        return value || _.isString(value) ? value : false;
@j0tunn 

меня глючит или это первый раз, когда ты заюзал `switch` в js ? 😄

2016-09-14 17:08 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, config);
ну и что ,  что она будет вызвана с 10ю? ну типо они проигнорятся, вот и все :)

как я понимаю, через `exactly` стоит проверять, когда у тебя у функции разное поведение в зависимости от аргументов,  а у тебя в итоге у функции одинаковое поведение, если она вызвана с 2мя параметрами и с 10ю

2016-09-14 17:09 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithExactly(decorateUrl, browser, {concat: false, url: {query: {foo: 'bar'}}});
calledWithMatch

2016-09-14 17:14 UTC, DudaGod commented on test/lib/url-decorator.js
> +
тут проблема, в `decorateUrl` значение `concat`-а попадает итоговое, то есть не `true`, а пустая строка.
Я в тестах на `index.js` проверил, что значение подменяется с `true` на пустую строку. И кажется что здесь достаточно проверить конкатенацию с любым разделителем. Не?

2016-09-14 17:50 UTC, DudaGod commented on test/lib/url-env-parser.js
> +    it('should throw error if env var has less than three delimiters', () => {
согласен по поводу не падать

2016-09-14 17:53 UTC, DudaGod commented on test/lib/url-env-parser.js
> +    it('should throw error if env var not set in snake case', () => {
У меня кстати bash ругается если ему передавать переменную среды окружения через тире. Говорит пошел в жопу.

2016-09-14 18:17 UTC, DudaGod commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) which is intended to add additional parameters to the current browser url. You can read more about plugins at [documentation](https:/
`to add additional parameters to the current browser url`
Я тут правильно указал его предназначение? Или все таки правильнее было бы указать:
`to add additional parameters to the test browser urls`
?

2016-09-14 18:19 UTC, DudaGod commented
/cc @eGavr @sipayRT @j0tunn @tormozz48 @rostik404 
guys you should look at this =)

2016-09-15 07:23 UTC, j0tunn commented on lib/index.js
> +        return value || _.isString(value) ? value : false;
😄

2016-09-15 08:39 UTC, eGavr commented
Договорились голосом, что API надо чуть передалать

2016-09-15 08:40 UTC, eGavr commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) which is intended to add additional parameters to the current browser url. You can read more about plugins at [documentation](https:/
второй вариант правильнее

2016-09-15 16:22 UTC, eGavr commented on README.md
> +For example you have next test url: `http://localhost/test/?name=hermione` and
после for example запятая не нужна?

2016-09-15 16:22 UTC, eGavr commented on README.md
> +PLATFORM=desktop HERMIONE_URL_QUERY_TEXT=ololo hermione
PLATFORM=desktop ?

2016-09-15 16:25 UTC, eGavr commented on README.md
> +In the case of using both possibilities of specifying additional url parameters, values from environment variables will be used.
А может упростим и напишем вот так:

Note: environment variables have higher priority than config values

?

2016-09-15 16:26 UTC, eGavr commented on README.md
> +### Concatenate url parameters
Concatination of url parameters ?

2016-09-15 16:27 UTC, eGavr commented on README.md
> +For instance, you have next url: `http://localhost/test/?name=hermione` and you want to concat current **name** query parameter with `harry` using `;` as delimiter.
to concat value of **name** query parameter with **harry** string using ...

2016-09-15 16:28 UTC, eGavr commented on README.md
> +As a result url will be look like: `http://localhost/test/?name=hermione;harry`
The result url will look like

2016-09-15 16:29 UTC, eGavr commented on README.md
> +For instance, you have next url: `http://localhost/test/?name=hermione` and you want to concat current **name** query parameter with `harry` using `;` as delimiter.
тут лучше двоеточие в конце, а не точку поставить, так как ты дальше показываешь конфиг

2016-09-15 16:30 UTC, eGavr commented on README.md
> +    enabled: 'true',
тут эту строку уже можно не писать,  так как по умолчанию плагин включен, кроме того тут должно быть boolean значение, а ты строку передаешь:)

2016-09-15 16:30 UTC, eGavr commented on README.md
> +    enabled: 'true',
не надо тут явно указывать `enabled`

2016-09-15 16:31 UTC, eGavr commented on README.md
> +If the concat is not set in config file or equal to `false`, then **name** query parameter in previous example will be overriden to: `http://localhost/test/?name=ron`.
if `concat` option is not set...

2016-09-15 16:32 UTC, eGavr commented on README.md
> +In case of setting concat as true, then url parameters will be concatenate without delimiter.
true в бэктики (ты false взял в прошлом примере, а тут не взял)

2016-09-15 16:32 UTC, eGavr commented on README.md
> +In case of setting concat as true, then url parameters will be concatenate without delimiter.
а че примера нету?

2016-09-15 16:32 UTC, eGavr commented on README.md
> +* **concat** (optional) `Boolean|String` - enable/disable concatenation of url parameters or specify the delimiter; by default is `false`
забыл убрать?

2016-09-15 16:33 UTC, eGavr commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, which will be added in each test url.`
тут надо раскрыть, что это за объект, не?

2016-09-15 16:41 UTC, DudaGod commented on README.md
> +* **concat** (optional) `Boolean|String` - enable/disable concatenation of url parameters or specify the delimiter; by default is `false`
да, сейчас удалю.

2016-09-15 16:45 UTC, DudaGod commented on README.md
> +As a result url will be look like: `http://localhost/test/?name=hermione;harry`
The result url will be look like - кажется так правильнее

2016-09-15 22:29 UTC, DudaGod commented on README.md
> +* **url** (optional) `Object` - the list of url parameters, which will be added in each test url.`
можно, раскрыл

2016-09-16 10:57 UTC, eGavr commented on README.md
> +Plugin for [hermione](https://github.com/gemini-testing/hermione) which is intended to add additional parameters to the test browser urls. You can read more about plugins at [documentation](https://g
is intended to change test urls in runtime.

2016-09-16 10:58 UTC, eGavr commented on README.md
> +## Configuration
я бы сделал графу `configuration` подпунктом абзаца `usage`

2016-09-16 11:00 UTC, eGavr commented on README.md
> +        * **queryParams** (optional) `Object` - names of query parameters
queryParams –> queryParam ?

2016-09-16 11:00 UTC, eGavr commented on README.md
> +        * **queryParams** (optional) `Object` - names of query parameters
names –> name

2016-09-16 11:00 UTC, eGavr commented on README.md
> +        * **queryParams** (optional) `Object` - names of query parameters
в единствено числе здесь везде...

2016-09-16 11:03 UTC, eGavr commented on README.md
> +            * **concat** (optional) `String|Boolean` - enable/disable concatenation of query parameters or specify the delimeter; by default is `false`
enable/disable concatenation of query parameters; if the value is string, existing query value will be concatenated with the defined value by the specified string

?

2016-09-16 11:03 UTC, eGavr commented on README.md
> +## Usage
Usage –> Examples ?

2016-09-16 11:05 UTC, eGavr commented on README.md
> +NB: environment variables have higher priority than config values.
NB ?

2016-09-16 11:06 UTC, eGavr commented on README.md
> +For instance, you have next url: `http://localhost/test/?name=hermione` and you want to concat value of **name** query parameter with **harry** string using `;` as delimiter:
as the delimeter

2016-09-16 11:06 UTC, DudaGod commented on README.md
> +NB: environment variables have higher priority than config values.
Nota Bene (обратить внимание) - известное сокращение. Не?

2016-09-16 11:07 UTC, eGavr commented on README.md
> +In case of setting concat as `true`, then url parameters will be concatenate without delimiter:
as –> to

?

слово then вроде лишнее

2016-09-16 11:08 UTC, eGavr commented on README.md
> +The result url will be look like: `http://localhost/test/?name=hermioneharry`
be лишнее слово

 и выше тоже

2016-09-16 11:09 UTC, eGavr commented on lib/index.js
> +    }
а зачем эта проверка?

2016-09-16 11:10 UTC, eGavr commented on lib/index.js
> +    validateConfigDeep(config);
эта функция `mutable`, то есть неявно меняет значение переданной переменной  `config` –  это не есть хорошо

2016-09-16 11:11 UTC, DudaGod commented on lib/index.js
> +    }
если в конфиге указать вот так:
```js
url: 'test'
```
то при валиации конфига мне ошибку бьет, то есть не могу удалить свойство. Либо эту проверку нужно в валидацию уносить либо просто откидывать.

2016-09-16 11:11 UTC, eGavr commented on lib/url-decorator.js
> +    return url.format(_.omit(parsedUri, 'search'));
зачем `omit` ?

може без лодаша просто выше сделаем

```js
delete parsedUri.search 
```

?

2016-09-16 11:13 UTC, DudaGod commented on lib/index.js
> +    validateConfigDeep(config);
ты имеешь ввиду название не соответвует?
`modificateConfig` ?

2016-09-16 11:42 UTC, eGavr commented on lib/index.js
> +    validateConfigDeep(config);
нет я имею ввиду, что создавать функции типа `mutable` – это плохая политика :)

2016-09-16 11:42 UTC, DudaGod commented on README.md
> +            * **concat** (optional) `String|Boolean` - enable/disable concatenation of query parameters or specify the delimeter; by default is `false`
enable/disable concatenation or specify the delimeter; by default is `false`

2016-09-16 12:24 UTC, DudaGod commented on lib/url-decorator.js
> +    return url.format(_.omit(parsedUri, 'search'));
тогда это 2 строки будет. Сначало delete, а затем format

2016-09-19 09:27 UTC, eGavr commented on README.md
> +NB: environment variables have higher priority than config values.
Просто **Note** или Remark** гораздо известнее :)

2016-09-19 10:15 UTC, eGavr commented on lib/url-env-parser.js
> +const parseUrlEnv = (result, value, key) => {
1. так как функция довольно сложная, то я бы написал дял нее JSDoc с полем `@example`, в котором бы написал, что она принимает на вход, а что на выход.

2. название переменной `key` ни о чем не говорит

3. давай эту функцию отцепим от функции `transform`, в которой она используется ?

```js
const _ = require('lodash');
const URL_ENV_START = require('./constants').URL_ENV_START;

/**
 * @param {String} value
 * @param {String} name
 *
 * @example
 * parseUrlEnv('query_exp_flags', 'awesome-value') → {query: {'exp_flags': {value: 'awesome-value'}}
 */
const parseUrlEnvVar = (value, name) => {
    const matched = name.match(/^(.*?)_(.+)/);

    return matched ? _.set({}, [matched[1], matched[2], 'value'], value) : {};
};

module.exports = () => {
    return _(process.env)
        .pickBy((value, key) => _.startsWith(key, URL_ENV_START))
        .mapKeys((envVal, envKey) => _.replace(envKey, URL_ENV_START, '').toLowerCase())
        .transform((result, envVal, envKey) => _.extend(result, parseUrlEnvVar(envVal, envKey)))
        .value();   
};
```

2016-09-19 10:16 UTC, eGavr commented on lib/url.js
> +    _validateQuery(query) {
эта функция не зависит от контекста, можно ее вынести из класса или сделать статической

2016-09-19 10:17 UTC, eGavr commented on lib/url.js
> +    _validateQuery(query) {
да и по факту она не валидирует значения,  а удаляет параметры без значений :) это я про то, что не очень удачно подобрано название

2016-09-19 10:18 UTC, eGavr commented on lib/url.js
> +    _validateQuery(query) {
а еще! как я понял.. эта функция mutable,  то есть меняет значение входного параметра, ничего не возвращает. вроде уже обсуждали, что плохо делать такие функции

2016-09-19 10:20 UTC, eGavr commented on lib/url.js
> +const configureQuery = (objValue, srcValue) => {
название так себе ... оно не говорит, что эта фукнция является каким-то кастомайзером для мержа...

2016-09-19 10:23 UTC, eGavr commented on lib/url.js
> +    return objValue && srcValue.concat !== false
а могут быть уже разве кейсы, когда `objValue === undefined`

2016-09-19 10:47 UTC, eGavr commented on lib/url.js
> +        this._validateQuery(query);
```js
query = _.omitBy(query, (obj) => !obj.value);
```

2016-09-19 10:48 UTC, eGavr commented on lib/url.js
> +        _.mergeWith(this._url.query, query, configureQuery);
```js
_.mergeWith(this._url.query, query, (objValue, src) => concat(src.concat)(objValue, src.value))
```

давай какое-то такое API попробуем, логику про concat вынесем в отдельный модуль

2016-09-19 10:50 UTC, eGavr commented on lib/url.js
> +        this._validateQuery(query);
это вместо функции `_validateQuery`

эту логику можно вынести в отдельную функцию, но назвать надо нормально.. что-то типо `omitWithoutValues`...

2016-09-19 11:05 UTC, DudaGod commented on lib/url.js
> +    return objValue && srcValue.concat !== false
да, если например указал переменную среды окружения `HERMIONE_URL_QUERY_MY_TEXT` и в текущем `uri` в `query` параметрах нет поля `my_text`. Тогда он будет `undefined`

2016-09-19 12:34 UTC, DudaGod commented
/cc @eGavr

2016-09-19 18:54 UTC, DudaGod commented
/cc @eGavr

2016-09-20 08:13 UTC, eGavr commented on README.md
> +For example, you have next test url: `http://localhost/test/?name=hermione` and
next –> the following ?

2016-09-20 08:13 UTC, eGavr commented on README.md
> +you want add additional query parameter via environment variable:
additional лищнее слово

2016-09-20 08:14 UTC, eGavr commented on README.md
> +            text: {
надо поддержать здесь возможность указания строки

2016-09-20 08:19 UTC, eGavr commented on README.md
> +In previous example you have seen how url parameters concatenate if `concat` is not set. The result will be the same if `concat` would be any value except `false`. Now we look how override url parame
1. how url parameters **are concatenated**...

2. how **to** override...

---------------

Ты не показал реальную конкатенацию, то есть не показал, что когда твой урл такой: `https://localhost/search/?exp_flags=1`, конфиг, например, такой:

```js
{
    url: {
        query: {
            exp_flags: '2'
        }
    }
}
```

то в результате урл будет такой:

`https://localhost/search/?exp_flags=1&exp_flags=2`

2016-09-20 08:20 UTC, eGavr commented on README.md
> +As a result url will be look like: `http://localhost/test/?name=harry`
тут, кажется,`be` не надо, так как `look like` – это уже глагол

2016-09-20 08:22 UTC, eGavr commented on lib/url-env-parser.js
> + * @param  {String} value of env var
of env vat лишнее, ИМХО

2016-09-20 08:22 UTC, eGavr commented on lib/url-env-parser.js
> + * @example
пустую надо пустой строкой отделить `@example` и `@params`

2016-09-20 08:23 UTC, eGavr commented on lib/url-env-parser.js
> +        .pickBy((value, key) => _.startsWith(key, URL_ENV_START))
key –> name

пропустил на прошлой итерации ревью :)

2016-09-20 08:24 UTC, eGavr commented on lib/url.js
> +const concatUrl = (currValue, srcValue, concat) => {
concatUrl –> concatQueryParams ?

2016-09-20 08:27 UTC, eGavr commented on lib/url.js
> +        _.mergeWith(this._url.query, query, (obj, src) => concatUrl(obj, src.value, src.concat));
obj –> currValue

2016-09-20 08:33 UTC, eGavr commented on lib/url.js
> +        : [currValue, srcValue];
тут есть проблема :)

а если `srcValue` – это массив? :)

ну я вот так указал в конфиге:

```js
{
    url: {
        query: {
            'exp_flags': [
                '1st-value',
                '2nd-value'
            ]
        }
    }
}
```

предлагаю так переписать:

```js
const concatQueryParams = (currValue, srcValue, concat) => {
    return concat && currValue
        ? [].concat(currValue, srcValue)
        : srcValue;
};
```

2016-09-20 08:33 UTC, eGavr commented on package.json
> +  "version": "1.0.0",
поменяй пока версию на `0.0.0`, а когда вольешь этот пулл-реквест, поменяешь обратно на `1.0.0` перед выпуском версии.

2016-09-20 08:37 UTC, eGavr commented on test/lib/index.js
> +        plugin(hermione, {url: {}});
`{url: {}}` – это не лишняя инфа для теста?

2016-09-20 08:38 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithMatch(decorateUrl, sinon.match.any, {query: {text: {concat: false}}});
я бы тут проверял, что не только `concat` прокидывается, но и `value` не теряется.

тогда можно будет использовать не `calledWithMatch`, `calledWith`

2016-09-20 08:39 UTC, eGavr commented on test/lib/index.js
> +        assert.calledWithMatch(decorateUrl, sinon.match.any, {query: {text: {concat: false}}});
нужен еще тест, когда в конфиге указаны параметры и через env указаны параметры, который проверяет, что они мержатся

2016-09-20 08:39 UTC, eGavr commented on test/lib/index.js
> +    });
я бы этот тест поставил выше, чем тесты про проверку конфига

2016-09-20 08:39 UTC, eGavr commented on test/lib/index.js
> +    describe('should do nothing if', () => {
а эту пачку тестов вообще самой первой

2016-09-20 08:42 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should not add url parameters which is not an object', () => {
вот как раз таки должен :)

`{text: 'foo'}` должен распарсится как `{text: {value: 'foo'}}` :)

2016-09-20 08:43 UTC, eGavr commented on lib/index.js
> +    const config = initConfig(opts.url, parseConfigFromEnv());
я тут подумал...

а давай функция `parseConfigFromEnv` будет принимать аргумент `process.env` ? кажется, что это как-то прямее выглядеть будет

2016-09-20 08:45 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it(`should return empty object if env vars starting with "${URL_ENV_START}" is invalid`, () => {
тут не очень правильно название теста...

`HERMIONE_URL_QUERY` – эта переменная не является невалидной  :) она просто не подходит под наш плагин, именно это и надо описать в названии теста

2016-09-20 08:46 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it('should return parsed object with not more than double nesting', () => {
ну тогда выше должен быть тест, который проверяет, что парсятся переменные, которые не являются ` double nesting' ? :)

2016-09-20 08:49 UTC, eGavr commented on test/lib/url.js
> +        sandbox.stub(url, 'parse').returns({search: '?query'});
не надо стабать :)

обычно мы стабаем то, что работает с реальными данными (например, какой-то http запрос или обращение к файловой системе), а здесь обычный парсинг строки, мы можем сами подать на вход нормальные данные, чтобы они распарсились как нам надо.

2016-09-20 08:52 UTC, eGavr commented on test/lib/url.js
> +    });
та и это вообще лишний тест, кажется

2016-09-20 08:53 UTC, eGavr commented on test/lib/url.js
> +    });
тоже лишний тест, вся эта штука проверится тестами ниже

2016-09-20 08:56 UTC, eGavr commented on test/lib/url.js
> +        });
а вот тут должно быть еще пару тестов:

1. передали в `updateQuery` объект, которого нет в `query` – он должен смержиться
2. передали в `updateQuery` объект, который есть в `query` – он должен доопределить существующий
3. передали в `updateQuery` объект, который есть в  `query`, но `concat` равен `false` – он должен переопределить существующий.

2016-09-20 11:23 UTC, DudaGod commented on test/lib/index.js
> +        plugin(hermione, {url: {}});
так нужно объект передать, чтобы тест дальше прошел и не вышел из функции

2016-09-20 11:26 UTC, DudaGod commented on test/lib/index.js
> +        assert.calledWithMatch(decorateUrl, sinon.match.any, {query: {text: {concat: false}}});
ну так это же предыдущий тест. В нем указано значение из env и из конфига. И в результате используется value из env.

2016-09-20 11:28 UTC, DudaGod commented on test/lib/index.js
> +    describe('should do nothing if', () => {
по моему в один из прошлых разов ты мне говорил их вниз пихать )

2016-09-20 11:45 UTC, DudaGod commented on lib/index.js
> +    const config = initConfig(opts.url, parseConfigFromEnv());
Не понял, а зачем так делать? Он же доступен в каждом файле и вряд ли понадобится передавать не все переменные среды окружения

2016-09-20 11:58 UTC, DudaGod commented on test/lib/url-env-parser.js
> +    it('should return parsed object with not more than double nesting', () => {
Так они все должны парсятся с двойной вложенностью, т.е.:
```js
HERMIONE_URL_QUERY_TEXT = 'test' => {query: {text: {value: 'test'}}}
// and
HERMIONE_URL_QUERY_MY_TEXT = 'test' => {query: {my_text: {value: 'test'}}}
```

2016-09-20 12:08 UTC, DudaGod commented on test/lib/url.js
> +        });
Так у меня есть же эти тесты в url-decorator.js
Перенести их сюда?

2016-09-20 12:45 UTC, eGavr commented on lib/index.js
> +    const config = initConfig(opts.url, parseConfigFromEnv());
очевиднее, когда функция что-то принимает, а затем что-то возвращает,  а не когда функция ничего не принимает, а потом вдруг что-то возвращает

2016-09-20 12:54 UTC, eGavr commented on lib/url.js
> +};
раскрытие конфига из опций должно происходить где-то выше, вместе с парсингом значений из переменных среды окружения

2016-09-21 08:12 UTC, tormozz48 commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=hermione` and you don't want override it:
you don't want **to** override it

2016-09-21 08:14 UTC, eGavr commented on README.md
> +you want add query parameter via environment variable:
want **to** add

2016-09-21 08:14 UTC, eGavr commented on README.md
> +            }
запятую тут забыл

2016-09-21 08:15 UTC, eGavr commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=hermione` and you don't want override it:
want **to**

2016-09-21 08:16 UTC, eGavr commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=hermione` and you don't want override it:
после `url` не надо вроде двоеточие

2016-09-21 08:17 UTC, eGavr commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=hermione` and you don't want override it:
ты пишешь, что мы переопределяем в этом примере, но пример про то, что ты конкатишь параметры

2016-09-21 08:17 UTC, DudaGod commented on README.md
> +            }
так я же ниже указываю второй вариант записи, т.е. либо этот либо нижний

2016-09-21 08:18 UTC, eGavr commented on README.md
> +Do not forget that you can do the same thing via environment variables. In this case concat value will be used from config to the same url parameter:
Do not forget that – лишняя фраза

2016-09-21 08:19 UTC, DudaGod commented on README.md
> +Suppose, you want to add query parameter `name` which is already present in your test url: `http://localhost/test/?name=hermione` and you don't want override it:
нет, я пишу что мы хотим добавить query параметр который уже есть в текущем урле и не хочу его переопределять.

2016-09-21 08:20 UTC, tormozz48 commented on lib/url.js
> +            src = _.isString(src) || _.isArray(src)
//cc @eGavr @rostik404 @sipayRT 

Вопрос к знатокам js. А ведь кажется что такую проверку можно заменить вот такой:
```
src = _.has(src, 'length') ? {value: src} : src; 
```

Или даже просто:
```
src = src.length ? {value: src} : src; 
```
при условии что у нас не пустой массив или строка.

Это просто размышления. Переделывать не нужно.

2016-09-21 08:27 UTC, eGavr commented on lib/url.js
> +        });
давай так сделаем:

```js
const concatValues = (currValue, srcValue, concat) => {
    if (_.isEmpty(currValue)) {
        return currValue;
    }

    return concat && currValue
        ? [].concat(currValue, srcValue)
        : srcValue;
};

const concatQueryParams = (currValue, src) => {
    src = _.isString(src) || _.isArray(scr)
        ? {value: src, concat: true} // тут лучше явно указывать, что `concat` – true
        : src;

    return concatValues(currValue, src.value, src.concat);
};

// ...
updateQuery(query) {
    _.mergeWith(this._url.query, concatQueryParams);

    return this;
}
// ...
```

2016-09-21 08:28 UTC, tormozz48 requested changes
Ждем правок в документации

2016-09-21 08:29 UTC, eGavr commented on test/lib/index.js
> +        plugin(hermione, {url: {}});
ну так передай пустой объект? :)

2016-09-21 08:34 UTC, eGavr commented on test/lib/index.js
> +});
и до сих пор нету теста, когда конфиг вот такой, например,

```js
{
    url: {
        query: {
            name: {
                value: 'hermione'
            }
        }
    }
}
```

а переменная такая `HERMIONE_URL_QUERY_TEXT=harry`

надо проверить, что на выходе такое

```js
{
    url: {
        query: {
            name: {
                value: 'hermione'
            },
            text: {
                value: 'harry'
            }
        }
    }
}
```

ну то есть убедиться, что конфиги мержаться

2016-09-21 08:35 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should add url parameters if they set as a string without value field', () => {
they **are** set

2016-09-21 08:35 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should add url parameters if they set as an array without value "field"', () => {
they **are** set

2016-09-21 08:36 UTC, eGavr commented on test/lib/url-decorator.js
> +    it('should not add url parameters if it set as an object without "value" field', () => {
it **is** set

2016-09-21 08:36 UTC, eGavr commented on test/lib/url-decorator.js
> +    });
на самом деле здесь два теста

1. первый тест проверяет, что переданная строка нормально распарсится и урл будет декорирован
2. переданная строка означает, что значения надо конкатить

2016-09-21 08:37 UTC, eGavr commented on test/lib/url-decorator.js
> +    });
здесь тоже два теста

1. первый тест проверяет, что переданный массив нормально распарсится и урл будет декорирован
2. переданный массив означает, что значения надо конкатить

2016-09-21 08:37 UTC, eGavr commented on test/lib/url-env-parser.js
> +        _.forEach(process.env, (value, key) => {
вот это до сих пор надо?

2016-09-21 08:38 UTC, eGavr commented on test/lib/url-env-parser.js
> +        process.env['HERMIONE_URL_QUERY'] = 'test';
в том то и дело, что теперь наша функция не зависит от `process.env`, она принимает какое-то значение, это не обязательно значения из `process.env`

2016-09-21 08:39 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it(`should return empty object if env vars starting with "${URL_ENV_START}" is not fit for plugin`, () => {
is not fit for –> do not fit plugin ?

2016-09-21 08:41 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it('should return parsed object with not more than double nesting', () => {
давай просто назовем

`should parse url param`

2016-09-21 08:41 UTC, eGavr commented on test/lib/url-env-parser.js
> +    it('should return parsed object with few query params', () => {
should parse several url params

P.S. указывать в названии то,  что эта штука парсит именно query нелогично, так как по факту она парсит все, что угодно

2016-09-21 08:44 UTC, eGavr commented on test/lib/url.js
> +        });
да, но конечно не один в один перенести. 
там (в тех тестах) ты подразумеваешь, что модуль `url` работает хорошо, подразумеваешь, что здесь ты его протестировал

2016-09-21 08:48 UTC, eGavr commented on lib/url.js
> +            src = _.isString(src) || _.isArray(src)
при втором варианте могут быть проблемы, когда src вдруг `undefined`.

первый вариант вроде должен работать.

@DudaGod если тебе ок, то можешь поправить, получается короче, но ИМХО чуть менее очевидно

2016-09-21 08:50 UTC, eGavr commented
Правь последние замечания, проверяй интеграционно и

/ok

2016-09-21 09:50 UTC, DudaGod commented on lib/url.js
> +            src = _.isString(src) || _.isArray(src)
мне проще читается мой вариант =)

2016-09-21 10:12 UTC, DudaGod commented on test/lib/url-decorator.js
> +    });
Ну у меня же есть два теста, в которых если сoncat - не задан или равен true, то значения конкатятся. Кажется он покрывает 2ой случай + я упростил этот тест, теперь значения указаны разные.

2016-09-21 10:26 UTC, eGavr commented on test/lib/url-decorator.js
> +    });
но у тебя нет теста на то, что строка раскрывается как `{value: 'строка', concat: true}`

аналогично с массивом `{value: ['1', '2'], concat: true}`

2016-09-21 10:27 UTC, eGavr commented on test/lib/url-decorator.js
> +    });
а предложенные мной тесты это проверят.

я не говорю, что ты сейчас эти кейсы не покрываешь, я говорю, что тест проверяет одновременно много и его стоит разбить на два

2016-09-21 10:35 UTC, DudaGod commented on test/lib/url-decorator.js
> +    });
я понял, добавил.

2016-09-21 22:32 UTC, merged